### ISSUE TITLE
Kubernetes Commands are not displayed, only docker containers.

### ISSUE THREAD

**Issue by guydog28** [eclipse-che/che-theia#1240]
Bug Description:

components of type: kubernetes do not display commands, while components of type: dockerimage do.  It used to work, but it has been a problem since somwhere in the 7.teens.

Current version tested: 7.38

To reproduce:
1. create a component of type dockerimage
2. create a command associated with dockerimage in step 1
3. confirm that command shows under the container in theia
4. create a component of type kubernetes
5. create a command associated with kubernetes component in step 4
6. confirm that command is not show under the kubernetes type container in theia

Expected behavior:
all commands should show in Theia

Runtime: 

Che Operator on Kubernetes 

Installation: 

chectl/latest

Environment:

Linux

Additional Context:

This is a huge problem for our team, they have to launch terminals and do everything manually.  all of our containers are type:kubernetes except for one, and we have like 10 containers in the workspace.  I am pretty sure this is the offending line of code, as it only displays for containers type and not kubernetes type:

https://github.com/eclipse-che/che-theia/blob/a2e698874048fa72fcc47336676e7a27bc4fbc34/plugins/containers-plugin/src/containers-service.ts#L49

**Comment by azatsarynnyy** [comment]
Hello @guydog28 
Thank you for your request!
Could you please provide more information about your problem? If you think there's a bug - try to follow a [bug report template](https://github.com/eclipse/che/issues/new/choose). Thanks!

**Comment by guydog28** [comment]
@azatsarynnyy I have updated the ticket.  Sorry I created this bug from the line of code, so it didn't use the form.

**Comment by benoitf** [comment]
The issue should be created at https://github.com/eclipse/che/issues
